version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    networks:
      - detercomms
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    networks:
      - detercomms
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_JMX_PORT=5029
    ports:
      - "5029:5029"
      - "9092:9092"
    depends_on:
      - zookeeper

  manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    networks:
      - detercomms
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - kafka

  consumer:
    build: .
    volumes:
      - "$PWD:/workdir"
    networks:
      - detercomms
    depends_on:
      - kafka

networks:
  detercomms:
